# Site settings
title: OSMF Capacity Planning
baseurl: /osmf-capacity-planning
# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
